### ISSUE TITLE
Error message while testing dmodman

### ISSUE THREAD

**Issue by jotoho** [dandels/dmodman#11]
I just installed dmodman `v0.2.2` (the latest tagged version on GitHub at the time of writing) and downloaded a few popular mods to test it.

Some time while I wasn't looking due to browsing and clicking download buttons on nexusmods, dmodman emitted some error message that messed up the GUI until quitting via `q` and restarting dmodman.

![Screenshot_20231029_091846](https://github.com/dandels/dmodman/assets/12120743/728fca79-afcd-4873-ad7b-2dc038478e5c)

The message seems to suggest that an error state was improperly processed, but you probably know more about what it means, than I do.

The list of mods I downloaded so far, in case the file or filename is relevant:
 - Unofficial Skyrim Special Edition Patch-266-4-2-9a-1685216241.7z
 - SkyUI_5_2_SE-12604-5-2SE.7z
 - Ordinator 9.31.0-1137-9-31-0-1635693140.zip
 - A Quality World Map - Classic with All Roads-5804-8-4CA.zip
 - Apocalypse - Ordinator Compatibility Patch WHY DO I HAVE TO CHANGE THE NAME-1090-.zip
 - Apocalypse v945-1090-9-45.zip
 - KS Hairdos SSE-6817-1-9-1645369981.7z
 - Mannaz 3.0.1-87219-3-0-1-1689266411.zip
 - Freyr 1.2.0-88043-1-2-0-1688923816.zip

If you already resolved this issue since release `v0.2.2`, feel free to just close the issue. :slightly_smiling_face:

**Comment by dandels** [comment]
This is probably the same issue as #7 which was fixed in the dev branch some time ago, but I never went ahead and made a bugfix release.

**Comment by dandels** [comment]
I finally went and did a new release. Can you reproduce the issue with the latest version?

**Comment by jotoho** [comment]
![Screenshot_20231104_110235](https://github.com/dandels/dmodman/assets/12120743/e7898ca9-273b-40d7-b10f-57e0e5d9954b)

I tried to reproduce the issue on `v0.2.3` and still got a warning message about file integrity but that seems intentional.

The UI is no longer breaking, so I think it's safe to say that this is no longer an issue.

Thank you for your help, @dandels!

**Comment by dandels** [comment]
> I tried to reproduce the issue on `v0.2.3` and still got a warning message about file integrity but that seems intentional.

This reminds me to update the readme to explain the hash checking problems. I probably need to check the code to remember it myself 😩
