### ISSUE TITLE
mismatching Cargo.toml and Cargo.lock

### ISSUE THREAD

**Issue by schnusch** [dandels/dmodman#13]
While trying to package this for <https://github.com/NixOS/nixpkgs> an error occured with `cargo build --frozen` (nix does not allow cargo to download dependencies on build and vendors thembeforehand):

```
error: the lock file /tmp/dmodman/Cargo.lock needs to be updated but --frozen was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --frozen flag and use --offline instead.
```

It seems `Cargo.toml` and `Cargo.lock` do not match in v0.2.3.

**Comment by dandels** [comment]
That's a bit awkward. It's a simple version number change in the Cargo.lock but it slipped me. I added it and moved the tag by a commit. Github seems to understand this just fine, and the source archives in the release got updated.
