### ISSUE TITLE
Cache directory not automatically created

### ISSUE THREAD

**Issue by LeonGr** [dandels/dmodman#5]
The program failed with error `Error: IOError { source: Os { code: 2, kind: NotFound, message: "No such file or directory" } }` until I created `~/.local/share/dmodman/` manually.

**Comment by dandels** [comment]
Well that's embarrassing, this has broken since I last tested it. I'll make a bugfix release ASAP.

**Comment by dandels** [comment]
Fixed in 0.2.1.
