### ISSUE TITLE
error when saving metadata: Invalid length 2, expected fewer elements in array /api/query/queriable.rs:20:96

### ISSUE THREAD

**Issue by Pulecz** [dandels/dmodman#7]
When downloading [Starfield mod 454 Enhanced Player Healthbar - WYOR](https://www.nexusmods.com/starfield/mods/454?tab=files) the file downloads fine but there is a bug with writing metadata.

Couldn't copy the text so [screenshot ](https://i.imgur.com/QOPUIEi.png) and if I didn't made a mistake in rewriting it:

```thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap() on an `Err` value: Error("Invalid length 2, expected fewer elements in array" line: 0, column: 0), src /api/query/queriable.rs:20:96```

EDIT: I am using the built binary from releases: https://github.com/dandels/dmodman/releases/download/v0.2.2/dmodman

**Comment by Pulecz** [comment]
The same issue now appears in [Cleanfield](https://www.nexusmods.com/starfield/mods/88/) with the file: 
Cleanfield.v.1.4.2-88-1-4-2-**1694021993**.rar

However a few minutes older file of same 1.4.2 version but with a different ID was fine: Cleanfield.v.1.4.2-88-1-4-2-**1694017633**.rar

I can provide the older file if needed, but it's probably not allowed on github. I am on IRC.

**Comment by dandels** [comment]
For other people possibly affected: I'm on something of a hiatus right now, but the latest dev branch has a fix for this until I make a proper release.

**Comment by luctius** [comment]
Not sure if this is the same issue, but [Skip Intro Video](nxm://starfield/mods/130/files/28?key=ews2Rv-1ptnhTCXRMKEKsg&
expires=1694852664&user_id=789012) still crashes on 'Error("missing field `name`", line: 0, column: 0)', src/api/query/queriable.rs:20:96'.

**Comment by dandels** [comment]
It's related, but needs an additional fix. In the first case the file has been uploaded under the same mod. In this case the file has previously been uploaded, then that mod page has been deleted and the file has been reuploaded under a different mod id. 

I implemented hash verification of downloads relatively recently and am not that surprised to run into weird corner cases. The hash lookup returns multiple mods and file details, and the deleted mod no longer has a name or some other fields which I assumed would be present. These fields aren't even used anywhere and there's a 4 year old comment saying some of them should probably be optional. :roll_eyes:

About this error message: all API requests and their deserialization is handled through the [Queriable](https://github.com/dandels/dmodman/blob/255e3e377fb929ae334e36d9224aa1a84fd887d0/src/api/query/queriable.rs) trait, and while it's nicely terse, the error messages it produces don't currently tell which response failed.
